name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@b243dc9a150810bcc68cb29635eae7c6f6367ca0

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@b243dc9a150810bcc68cb29635eae7c6f6367ca0

  verify-renovate:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@b243dc9a150810bcc68cb29635eae7c6f6367ca0

  verify-build-nuget:
    uses: ./.github/workflows/reusable-build-nuget-package.yaml
    with:
      version: 0.0.1
      configuration: Release
