name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@1a5d81bd9b2876415f444f463b755e1e4e7f4ca9

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@1a5d81bd9b2876415f444f463b755e1e4e7f4ca9

  verify-renovate:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@1a5d81bd9b2876415f444f463b755e1e4e7f4ca9

  verify-build-nuget:
    uses: ./.github/workflows/reusable-build-nuget-package.yaml
    with:
      version: 0.0.1
      configuration: Release
