name: Verifies PR are ready for merge

on:
  pull_request:
    branches:
      - main

jobs:
  verify-devcontainer:
    uses: project-origin/.github/.github/workflows/reusable-verify-devcontainer.yaml@e68140da2a4438754f6bb23b2067a252d7557148

  verify-code:
    uses: project-origin/.github/.github/workflows/reusable-verify-code.yaml@e68140da2a4438754f6bb23b2067a252d7557148

  verify-renovate:
    uses: project-origin/.github/.github/workflows/reusable-verify-renovate.yaml@e68140da2a4438754f6bb23b2067a252d7557148

  verify-build-nuget:
    uses: ./.github/workflows/reusable-build-nuget-package.yaml
    with:
      version: 0.0.1
      configuration: Release
