name: Build Rust artifacts

on:
  workflow_call:
    inputs:
      path:
        description: 'Path to the Rust project'
        required: true
        type: string

jobs:
  build-native-rust-artifacts:
    name: Build release (${{ matrix.target }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows-latest
            target: aarch64-pc-windows-msvc

          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu

          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-13
            target: aarch64-apple-darwin

    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Install Rust toolchain
        run: |
          rustup update --no-self-update stable
          rustup target add ${{ matrix.target }}
          rustup component add rust-src

      - name: Install aarch64-linux toolchain
        if: matrix.target == 'aarch64-unknown-linux-gnu'
        run: |
          sudo apt-get update
          sudo apt-get install gcc-aarch64-linux-gnu
          mkdir .cargo
          cat << EOF > .cargo/config.toml
          [target.aarch64-unknown-linux-gnu]
          linker = "aarch64-linux-gnu-gcc"
          EOF

      - name: Build rust package
        shell: bash
        working-directory: ${{ inputs.path }}
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: ${{ matrix.target }}
          retention-days: 1
          path: |
            ${{ inputs.path }}/target/${{ matrix.target }}/release/lib*.so
            ${{ inputs.path }}/target/${{ matrix.target }}/release/lib*.dylib
            ${{ inputs.path }}/target/${{ matrix.target }}/release/*.dll
