name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@73c7ca3a1464da66006a8116ebc3cd3323218e76
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
