name: SonarCloud

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  analyse:
    uses: project-origin/.github/.github/workflows/reusable-sonarcloud.yaml@e8bd94cc320224bb68c829937a63eea973c7007d
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
